### ISSUE TITLE
Publish 1.2.0 to npm

### ISSUE THREAD

**Issue by styfle** [Songkeys/tsconfig-to-swcconfig#2]
npm version is 1.1.0: https://www.npmjs.com/package/tsconfig-to-swcconfig

github version is 1.2.0: https://github.com/Songkeys/tsconfig-to-swcconfig/blob/e826573677606b9fcd9db70d684d4cf6bac28284/package.json#L3

**Comment by songkeys** [comment]
Sorry about this. I've published v1.2.0 to npm just now. Thank you.
