### ISSUE TITLE
Support `"module": "node16"/"nodenext"`

### ISSUE THREAD

**Issue by jfirebaugh** [Songkeys/tsconfig-to-swcconfig#23]
Currently, tsconfig-to-swcconfig always outputs `"module": { "type": "commonjs" }` when the input tsconfig uses `"module": "node16"` or `"module": "nodenext"`. Instead, if the nearest `package.json` has `"type": "module"`, it should output `"module": { "type": "es6" }`.

**Comment by songkeys** [comment]
Thank you for bringing up this issue. It has been fixed and released in version [`v2.8.0`](https://github.com/Songkeys/tsconfig-to-swcconfig/releases/tag/v2.8.0).

**Comment by jfirebaugh** [comment]
Well, now `"module": "node16"` and `"module": "nodenext"` are _always_ considered ES6. The fix should be more like:

```
	const es6Modules = [
		'es2015',
		'es2020',
		'es2022',
		'esnext',
		'none',
	] as const
	if (es6Modules.includes(module as any)) {
		return 'es6'
	}

        const nodeModules = ['node16', 'nodenext'] as const
	if (nodeModules.includes(module as any) && getPackageJson(cwd)?.type === 'module') {
		return 'es6'
	}
```

**Comment by songkeys** [comment]
Thank you!
Would you like to send a Pull Request to address this issue?

**Comment by jfirebaugh** [comment]
Sure, thanks for the encouragement: https://github.com/songkeys/tsconfig-to-swcconfig/pull/24
