### ISSUE TITLE
support jsc.baseUrl

### ISSUE THREAD

**Issue by beckend** [Songkeys/tsconfig-to-swcconfig#4]
Currently it is very selective and does not include this.

**Comment by songkeys** [comment]
Thanks for reminding. I've fixed it. 👍

I'm keeping two set of configs in sync as much as possible. However some fields in tsconfig are not fully supported by swc. 
 Vice versa. But they are iterating. If anything is out of sync please let me know.

**Comment by beckend** [comment]
In that case, there are a few more typescript related options in https://swc.rs/docs/configuration/compilation

**Comment by songkeys** [comment]
Could you be more specific?

**Comment by beckend** [comment]
```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true,
      "dynamicImport": true
    }
  }
}
```
