### ISSUE TITLE
Difference between strict and strictMode?

### ISSUE THREAD

**Issue by Smankusors** [Songkeys/tsconfig-to-swcconfig#7]
Hey, thanks for making this tool 👍 

But I wondering, what's difference between `strict` and `strictMode`? If I used the code below

```
const swcConfig = convertTsConfig({
  module: 'commonjs',
  target: 'es2015'
})
```

It generates config below

```
{
  "sourceMaps": "inline",
  "module": {
    "type": "commonjs",
    "strict": false,
    "strictMode": true,
    "noInterop": true
  },
  "jsc": {
    "externalHelpers": false,
    "target": "es2015",
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": false,
      "dynamicImport": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": false,
      "react": {
        "throwIfNamespace": false,
        "development": false,
        "useBuiltins": false,
        "pragma": "React.createElement",
        "pragmaFrag": "React.Fragment",
        "importSource": "react"
      }
    },
    "keepClassNames": false
  }
}
```

Why `strict: false` and `strictMode: true`? I can't find any documentation about this option... 🤕 

Thanks,

**Comment by songkeys** [comment]
Hi!

You can find the definitions on swc.rs: https://swc.rs/docs/configuration/modules#strict vs https://swc.rs/docs/configuration/modules#strictmode.

In tsconfig, `strict` is controlled `strict`, and `strictMode` by `alwaysStrict || !noImplicitUseStrict`.

`strict`, `alwaysStrict`, `noImplicitUseStrict` are `false` by default in tsconfig. So you will get that output.

**Comment by Smankusors** [comment]
ooh.... I see

Thankks for the link, seems like my Google-fu is not good enough 😅
