### ISSUE TITLE
any plan to have a cli?

### ISSUE THREAD

**Issue by sayjeyhi** [Songkeys/tsconfig-to-swcconfig#9]

**Comment by songkeys** [comment]
We have a cli tool in this project: https://github.com/Songkeys/tswc

**Comment by Distortedlogic** [comment]
I think he might have meant a cli command to run the conversion of tsconfig to swcrc .. at least thats why im in the thread lol

**Comment by songkeys** [comment]
Reasonable! I just added cli usage in v2.4.0. Let me know if it resolves your needs.

doc: https://github.com/Songkeys/tsconfig-to-swcconfig#cli
